project:
  type: website
  resources:
    - robots.txt
    - staticwebapp.config.json

website:
  title: "MyYearInData"
  site-url: "https://www.myyearindata.com"
  description: "Data engineering, architecture, and AI insights from Scott Bell. Exploring governance, security, and the evolving landscape of intelligent systems."
  open-graph:
    locale: en_GB
    site-name: MyYearInData
  twitter-card:
    card-style: summary_large_image
    creator: "@fusionet24"
    site: "@fusionet24"
  navbar:
    right:
      - about.qmd
      - text: AIOps Journey
        href: aiops-journey.qmd
      - text: DailyDatabricks
        href: https://dailydatabricks.tips
      - talks.qmd
      - icon: github
        href: https://github.com/fusionet24
      - icon: twitter
        href: https://twitter.com/fusionet24
      - icon: Mastodon
        text: Mastodon
        href: https://techhub.social/@fusionet24
      - icon: rss
        href: index.xml

filters:
  - _filters/content-label.lua

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

